import '../model/team.dart';

final allTeams = <Team>[
  Team(
      name: 'Al Raed',
      nameAr: 'الرائد',
      teamApiId: '363',
      teamId: '1',
      logo: 'https://jdwel.com/image/teams/sau_al_raed.png',
      dataId: '23280'),
  Team(
      name: 'Al Wahda',
      nameAr: 'الوحدة',
      teamApiId: '2513',
      teamId: '5',
      logo: 'https://jdwel.com/image/teams/sau_al_wahda.png',
      dataId: '23284'),
  Team(
      name: 'Al Ittifaq',
      nameAr: 'الإتفاق',
      teamApiId: '10010',
      teamId: '10',
      logo: 'https://jdwel.com/image/teams/sau_al_ittifaq.png',
      dataId: '23288'),
  Team(
      name: 'Al Khaleej',
      nameAr: 'الخليج',
      teamApiId: '12216',
      teamId: '765',
      logo: 'https://jdwel.com/image/teams/sau_al_khaleej.png',
      dataId: '23295'),
  Team(
      name: 'Al Ittihad',
      nameAr: 'الاتحاد',
      teamApiId: '476',
      teamId: '2',
      logo: 'https://jdwel.com/image/teams/sau_al_ittihad.png',
      dataId: '23281'),
  Team(
      name: 'Abha',
      nameAr: 'أبها',
      teamApiId: '5618',
      teamId: '760',
      logo: 'https://jdwel.com/image/teams/sau_abha_v2.png',
      dataId: '23292'),
  Team(
      name: 'Al Batin',
      nameAr: 'الباطن',
      teamApiId: '10264',
      teamId: '11',
      logo: 'https://jdwel.com/image/teams/sau_al_batin_v2.png',
      dataId: '23287'),
  Team(
      name: 'Al Shabab',
      nameAr: 'الشباب',
      teamApiId: '16184',
      teamId: '13',
      logo: 'https://jdwel.com/image/teams/sau_al_shabab_v2.png',
      dataId: '23289'),
  Team(
      name: 'Al Taawon',
      nameAr: 'التعاون',
      teamApiId: '2392',
      teamId: '3',
      logo: 'https://jdwel.com/image/teams/sau_al_taawon_v2.png',
      dataId: '23282'),
  Team(
      name: 'Al Fateh',
      nameAr: 'الفتح',
      teamApiId: '5891',
      teamId: '6',
      logo: 'https://jdwel.com/image/teams/sau_al_fateh.png',
      dataId: '23285'),
  Team(
      name: 'Al Tai',
      nameAr: 'الطائي',
      teamApiId: '10660',
      teamId: '763',
      logo: 'https://jdwel.com/image/teams/sau_al_taee_v2.png',
      dataId: '23291'),
  Team(
      name: 'Dhamk',
      nameAr: 'ضمك',
      teamApiId: '17712',
      teamId: '774',
      logo: 'https://jdwel.com/image/teams/sau_dhamk_v2.png',
      dataId: '23290'),
  Team(
      name: 'Al Nassr',
      nameAr: 'النصر',
      teamApiId: '2506',
      teamId: '4',
      logo: 'https://jdwel.com/image/teams/sau_al_nassr_v2.png',
      dataId: '23283'),
  Team(
      name: 'Al Hilal',
      nameAr: 'الهلال',
      teamApiId: '7011',
      teamId: '8',
      logo: 'https://jdwel.com/image/teams/sau_al_hilal.png',
      dataId: '23286'),
  Team(
      name: 'Al Adalh',
      nameAr: 'العدالة',
      teamApiId: '10677',
      teamId: '764',
      logo: 'https://jdwel.com/image/teams/sau_al_adalh.png',
      dataId: '23294'),
  Team(
      name: 'Al Feiha',
      nameAr: 'الفيحاء',
      teamApiId: '17724',
      teamId: '16',
      logo: 'https://jdwel.com/image/teams/sau_al_feiha_v2.png',
      dataId: '23293'),
];
